# -*- coding: utf-8 -*-
# Generated by GenryModEngine. Edit story.txt, not this file.

init python:
    def genry_resolve_music(name):
        genry_music_aliases = {
            "lightness radio edit": "lightness_radio_bus",
            "lightness radio": "lightness_radio_bus",
            "lightness_radio": "lightness_radio_bus",
            "lightness-radio": "lightness_radio_bus",
            "lightness_radio_edit": "lightness_radio_bus",
            "lightness-radio-edit": "lightness_radio_bus",
            "radio_lightness": "lightness_radio_bus",
            "lightness": "lightness",
        }
        genry_music_builtin_paths = {
            "lightness_radio_bus": "sound/music/lightness_radio.ogg",
            "lightness": "sound/music/lightness.ogg",
        }
        key = str(name).strip()
        alias_key = key.lower().replace("_", " ").replace("-", " ")
        key = genry_music_aliases.get(alias_key, genry_music_aliases.get(key.lower(), key))
        try:
            return music_list.get(key, genry_music_builtin_paths.get(key, None))
        except Exception:
            return genry_music_builtin_paths.get(key, None)

    def genry_resolve_audio_expr(expr):
        try:
            return eval(expr, globals(), audio.__dict__)
        except Exception:
            pass
        try:
            return eval(expr, globals())
        except Exception:
            return None

    def genry_sprite_time_matrix():
        try:
            mode = str(persistent.sprite_time)
        except Exception:
            mode = "day"
        mode = mode.lower().strip()
        if mode in ("night", "ночь"):
            return SaturationMatrix(0.62) * BrightnessMatrix(-0.10) * TintMatrix("#6a78c8")
        if mode in ("sunset", "evening", "вечер", "закат"):
            return SaturationMatrix(0.86) * BrightnessMatrix(0.02) * TintMatrix("#ffd08a")
        if mode in ("prolog", "prologue", "пролог"):
            return SaturationMatrix(0.72) * BrightnessMatrix(-0.02) * TintMatrix("#b8c7ff")
        return IdentityMatrix()

    def genry_warn_missing_audio(kind, name):
        try:
            renpy.log("Genry missing %s: %s" % (kind, name))
        except Exception:
            pass

init:
    $ mods["genry_golden"] = u"Golden"
    $ genry = Character(u"Генри", color="#ffcc66")
    $ scar = Character(u"Шрам", color="#ff6666")
    $ dissolve2 = Dissolve(2.0)
    $ fade2 = Fade(0.45, 0.0, 0.45)
    $ fade3 = Fade(0.75, 0.0, 0.75)
    image genry_flash = Solid("#ffffff")
    image genry_black = Solid("#000000")
    image genry_note_dim = Solid("#000000")
    image genry_phone_body = "mods/genry_golden/images/genry_phone_body.png"
    style genry_thought is default:
        size 38
        color "#eef6ff"
        outlines [(2, "#000000", 0, 0)]
    image genry_chapter_back = "images/anim/backdrop/back.jpg"
    image genry_chapter_noise = Animation("images/anim/backdrop/1.png", 0.08, "images/anim/backdrop/2.png", 0.08, "images/anim/backdrop/3.png", 0.08)
    image genry_p_snow = Solid("#ffffffdd", xsize=6, ysize=6)
    image genry_p_rain = Solid("#bcd8ffcc", xsize=2, ysize=18)
    image genry_p_leaf = Solid("#7bbf3aee", xsize=10, ysize=6)
    image genry_p_heart = Solid("#ff7bb0ee", xsize=8, ysize=8)
    image genry_p_spark = Solid("#ffe066ee", xsize=4, ysize=4)
    image genry_p_dust = Solid("#c9ccd6aa", xsize=4, ysize=4)
    image genry_weather_snow = SnowBlossom("genry_p_snow", count=60, border=60, xspeed=(15, 30), yspeed=(40, 120))
    image genry_weather_rain = SnowBlossom("genry_p_rain", count=120, border=80, xspeed=(0, 0), yspeed=(1500, 1700), fast=True)
    image genry_weather_leaf = SnowBlossom("genry_p_leaf", count=40, border=80, xspeed=(20, 60), yspeed=(80, 160))
    image genry_weather_heart = SnowBlossom("genry_p_heart", count=30, border=60, xspeed=(10, 40), yspeed=(60, 140))
    image genry_weather_spark = SnowBlossom("genry_p_spark", count=50, border=60, xspeed=(20, 40), yspeed=(30, 90))
    image genry_weather_dust = SnowBlossom("genry_p_dust", count=45, border=60, xspeed=(10, 30), yspeed=(20, 70))

screen genry_screen_menu(title, items, bg_image=None, logo_image=None, char_image=None, char_x=0.82, char_y=1.0, panel_x=0.78, panel_color="#111827", accent="#7dd3fc", panel_alpha=0.88, button_color="#182131", button_hover="#2b5c8f", text_color="#eef6ff", title_size=38, menu_width=470, subtitle="", hint="", footer="", dim_alpha=0.45):
    tag menu
    modal True
    if bg_image:
        add bg_image
    else:
        add Solid("#05070b")
    add Transform(Solid("#000000"), alpha=dim_alpha)
    if char_image:
        add char_image xalign char_x yalign char_y
    if logo_image:
        add Transform(logo_image, fit="contain", xysize=(360, 150)) xalign 0.08 yalign 0.10
    if footer:
        text footer xalign 0.04 yalign 0.95 size 18 color "#dbeafe"
    frame:
        background Transform(Solid(panel_color), alpha=panel_alpha)
        xalign panel_x
        yalign 0.5
        xminimum 380
        xmaximum menu_width
        xpadding 28
        ypadding 26
        vbox:
            spacing 14
            if logo_image:
                null height 34
            text title size title_size color accent xmaximum (menu_width - 60)
            if subtitle:
                text subtitle size 20 color text_color xmaximum (menu_width - 60)
            if hint:
                text hint size 16 color "#9fb3c8" xmaximum (menu_width - 60)
            null height 8
            viewport:
                mousewheel True
                scrollbars "vertical"
                ymaximum 520
                vbox:
                    spacing 10
                    for caption, target in items:
                        button:
                            if target:
                                action Return(target)
                            else:
                                action Return(None)
                            xfill True
                            ypadding 14
                            xpadding 18
                            background Solid(button_color)
                            hover_background Solid(button_hover)
                            text caption size 26 color text_color

screen genry_notify_popup(title, body, icon=None, panel_color="#111827", accent="#7dd3fc", side="right"):
    zorder 95
    if side == "left":
        frame:
            at genry_notify_left
            background Transform(Solid(panel_color), alpha=0.93)
            xsize 520
            xpadding 18
            ypadding 14
            use genry_notify_popup_body(title, body, icon, accent)
    elif side == "top":
        frame:
            at genry_notify_top
            background Transform(Solid(panel_color), alpha=0.93)
            xsize 560
            xpadding 18
            ypadding 14
            use genry_notify_popup_body(title, body, icon, accent)
    elif side == "bottom":
        frame:
            at genry_notify_bottom
            background Transform(Solid(panel_color), alpha=0.93)
            xsize 560
            xpadding 18
            ypadding 14
            use genry_notify_popup_body(title, body, icon, accent)
    else:
        frame:
            at genry_notify_right
            background Transform(Solid(panel_color), alpha=0.93)
            xsize 520
            xpadding 18
            ypadding 14
            use genry_notify_popup_body(title, body, icon, accent)

screen genry_notify_popup_body(title, body, icon, accent):
    hbox:
        spacing 14
        if icon:
            add Transform(icon, fit="contain", xysize=(64, 64)) yalign 0.5
        vbox:
            spacing 4
            text title size 22 color accent outlines [(1, "#000000", 0, 0)]
            text body size 19 color "#eef6ff" xmaximum 405 outlines [(1, "#000000", 0, 0)]

screen genry_music_player(tracks, title="Музыкальный плеер", accent="#7dd3fc"):
    modal True
    add Solid("#000000cc")
    frame:
        xalign 0.5
        yalign 0.5
        xmaximum 760
        background Solid("#0f141b")
        xpadding 30
        ypadding 26
        vbox:
            spacing 12
            text title size 34 color accent
            null height 6
            viewport:
                mousewheel True
                scrollbars "vertical"
                ymaximum 420
                vbox:
                    spacing 8
                    for track_name, track_file in tracks:
                        textbutton track_name action Play("music", track_file) text_size 24 text_color "#eef6ff" text_hover_color accent xminimum 320
            null height 10
            hbox:
                spacing 24
                textbutton "Стоп" action Stop("music", fadeout=1.0) text_size 24 text_color "#eef6ff" text_hover_color accent
                textbutton "Закрыть" action Return(0) text_size 24 text_color "#eef6ff" text_hover_color accent

screen genry_phone(messages, contact="СМС", accent="#7dd3fc"):
    zorder 60
    frame:
        at genry_phone_in
        xalign 0.5
        yalign 0.5
        xsize 640
        ysize 820
        background "genry_phone_body"
        padding (24, 58, 24, 46)
        vbox:
            spacing 0
            frame:
                xfill True
                background Solid("#161b24")
                padding (18, 12)
                hbox:
                    spacing 14
                    frame:
                        xysize (58, 58)
                        background Solid(accent)
                        padding (0, 0)
                        text contact[0:1].upper() xalign 0.5 yalign 0.5 size 30 color "#0b1018"
                    vbox:
                        yalign 0.5
                        spacing 2
                        text contact size 28 color accent
                        if _genry_phone_typing:
                            text "печатает…" size 16 color "#9fb3c8"
                        else:
                            text "● на связи" size 16 color "#7CFC9A"
            viewport:
                mousewheel True
                scrollbars "vertical"
                yfill True
                yinitial 1.0
                vbox:
                    spacing 10
                    xfill True
                    null height 10
                    for msg_side, msg_name, msg_body, msg_time, msg_status in messages:
                        if msg_side == "me":
                            vbox:
                                xalign 1.0
                                spacing 1
                                frame:
                                    at genry_msg_in
                                    xalign 1.0
                                    xmargin 14
                                    xmaximum 460
                                    background Solid("#2f6fed")
                                    padding (16, 10)
                                    text msg_body color "#ffffff" size 24
                                text (msg_time + "  " + msg_status) xalign 1.0 xoffset -18 size 14 color "#9fb3c8"
                        else:
                            vbox:
                                xalign 0.0
                                spacing 1
                                frame:
                                    at genry_msg_in
                                    xalign 0.0
                                    xmargin 14
                                    xmaximum 460
                                    background Solid("#1c2733")
                                    padding (16, 10)
                                    vbox:
                                        spacing 2
                                        text msg_name color accent size 18
                                        text msg_body color "#eef6ff" size 24
                                text msg_time xalign 0.0 xoffset 18 size 14 color "#9fb3c8"
                    if _genry_phone_typing:
                        frame:
                            at genry_msg_in
                            xalign 0.0
                            xmargin 14
                            background Solid("#1c2733")
                            padding (18, 12)
                            text "● ● ●" color "#9fb3c8" size 22
                    null height 10

# Современное анимированное меню выбора. Это штатный для Ren'Py 'screen choice',
# который вызывает любой 'menu:' (наш 'выбор' остаётся menu: -> rollback цел).
# Кнопки выезжают (genry_choice_in), есть hover. Оформление в стиле БЛ/модов.
screen choice(items):
    zorder 50
    modal True
    add Solid("#00000099")
    vbox:
        at genry_choice_in
        xalign 0.5
        yalign 0.5
        spacing 16
        for i in items:
            button:
                action i.action
                xsize 680
                ypadding 18
                xpadding 30
                background Solid("#16243a")
                hover_background Solid("#2a4f86")
                text i.caption xalign 0.5 size 28 color "#eef6ff"

transform genry_sprite_time_tint:
    matrixcolor genry_sprite_time_matrix()
transform genry_filter_none:
    matrixcolor IdentityMatrix()
transform genry_filter_sepia:
    matrixcolor SepiaMatrix()
transform genry_filter_gray:
    matrixcolor SaturationMatrix(0.0)
transform genry_filter_night:
    matrixcolor (SaturationMatrix(0.55) * BrightnessMatrix(-0.08) * TintMatrix("#6a78c8"))
transform genry_filter_warm:
    matrixcolor TintMatrix("#ffcf8f")
transform genry_filter_cold:
    matrixcolor TintMatrix("#9fc6ff")
transform genry_filter_dream:
    matrixcolor (SaturationMatrix(0.55) * BrightnessMatrix(0.12))
transform genry_filter_faded:
    matrixcolor (SaturationMatrix(0.7) * ContrastMatrix(0.9))
transform genry_filter_horror:
    matrixcolor (SaturationMatrix(0.3) * ContrastMatrix(1.2) * BrightnessMatrix(-0.12))
transform genry_phone_in:
    yoffset 780 alpha 0.0
    easeout 0.4 yoffset 0 alpha 1.0
transform genry_msg_in:
    alpha 0.0 yoffset 16
    easein 0.18 alpha 1.0 yoffset 0
transform genry_choice_in:
    alpha 0.0 yoffset 28
    easeout 0.28 alpha 1.0 yoffset 0
transform genry_thought_float(x=0.5, y=0.18, seconds=3.0):
    xalign x yalign y alpha 0.0 yoffset 22
    easeout 0.35 alpha 1.0 yoffset 0
    pause seconds
    easein 0.45 alpha 0.0 yoffset -22
transform genry_notify_right:
    on show:
        xalign 1.0 yalign 0.08 xoffset 560 alpha 0.0
        easeout 0.35 xoffset -28 alpha 1.0
    on hide:
        easein 0.22 xoffset 560 alpha 0.0
transform genry_notify_left:
    on show:
        xalign 0.0 yalign 0.08 xoffset -560 alpha 0.0
        easeout 0.35 xoffset 28 alpha 1.0
    on hide:
        easein 0.22 xoffset -560 alpha 0.0
transform genry_notify_top:
    on show:
        xalign 0.5 yalign 0.0 yoffset -180 alpha 0.0
        easeout 0.35 yoffset 28 alpha 1.0
    on hide:
        easein 0.22 yoffset -180 alpha 0.0
transform genry_notify_bottom:
    on show:
        xalign 0.5 yalign 1.0 yoffset 180 alpha 0.0
        easeout 0.35 yoffset -28 alpha 1.0
    on hide:
        easein 0.22 yoffset 180 alpha 0.0

label genry_golden:
    jump s


label s:
    ""
    jump s_next

label s_next:
    "2"

    return
label s_next:
    "x"

    return
label t:
    jump t_next

label t_next:
    "y"
    stop music fadeout 2
    stop ambience fadeout 2
    stop sound
    return
