# -*- coding: utf-8 -*-
"""scr_tables.py + data/es_catalog.json -> src/core/ScreenplayTables.inc (the C++ side of «пиши как сценарий»).
Run from anywhere: py -3 tools/screenplay/gen_tables.py"""
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
from scr_tables import *


def n(s):
    return s.lower().replace('ё', 'е').strip()


def q(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


out = ['// Generated by tools/screenplay/gen_tables.py from scr_tables.py and data/es_catalog.json - do not edit.',
       '// «Пиши как сценарий»: the words the expander understands and the ES sprites/backgrounds it resolves to.', '']


def strs(name, items):
    out.append('static const char* const %s[] = {' % name)
    line = '   '
    for it in items:
        piece = ' ' + q(it) + ','
        if len(line) + len(piece) > 118:
            out.append(line)
            line = '   '
        line += piece
    out.append(line + ' nullptr};')
    out.append('')


def pairs(name, items):
    out.append('static const ScrPair %s[] = {' % name)
    for a, b in items:
        out.append('    {%s, %s},' % (q(a), q(b)))
    out.append('    {nullptr, nullptr}};')
    out.append('')


cat = json.load(open(os.path.join(ROOT, 'data', 'es_catalog.json'), encoding='utf-8'))
strs('kScrSprites', sorted(cat['sprites']))
strs('kScrBgs', sorted(k[3:] for k in cat['images'] if k.startswith('bg ')))
pairs('kScrChains', [(k, ' '.join(v)) for k, v in CHAINS.items()])
pairs('kScrStronger', STRONGER.items())
pairs('kScrWeaker', WEAKER.items())
lex = []
for p, c in EMO_WORDS: lex.append(('emo:' + c, n(p)))
for p, c in OUTFIT_WORDS: lex.append(('outfit:' + c, n(p)))
for p, c in OV_WORDS: lex.append(('ov:' + c, n(p)))
for p, c in ACC_WORDS: lex.append(('acc:' + c, n(p)))
for p, c in DIST_WORDS: lex.append(('dist:' + c, n(p)))
for p, c in POS_PHRASES: lex.append(('pos:' + c, n(p)))
for p in ENTER_WORDS: lex.append(('enter:' + ('fast' if p in FAST_EXIT else ''), n(p)))
for p in EXIT_WORDS: lex.append(('exit:' + ('fast' if p in FAST_EXIT else ''), n(p)))
for cat_, words in (('offscreen', OFFSCREEN), ('thought', THOUGHT), ('punch', PUNCH), ('ignore', IGNORE),
                    ('strong', STRONG_WORDS), ('weak', WEAK_WORDS), ('neg', NEGATE)):
    for p in words: lex.append((cat_ + ':', n(p)))
pairs('kScrLex', lex)
pairs('kScrOutfitGroups', [(k, ' '.join(v)) for k, v in OUTFIT_GROUPS.items()])
strs('kScrOutfitPriority', OUTFIT_PRIORITY)
pairs('kScrDefaultLook', [(k, '%s|%s' % v) for k, v in DEFAULT_LOOK.items()])
pairs('kScrDirections', [(n(a), b) for a, b in DIRECTION_WORDS])
pairs('kScrPlaces', [(k, '%s|%s|%s' % (v[0], v[1] or '', v[2] or '')) for k, v in PLACES.items()])
pairs('kScrPlaceWords', [(n(a), b) for a, b in PLACE_WORDS])
pairs('kScrTimeWords', [(n(a), b) for a, b in TIME_WORDS])
pairs('kScrTimeRu', TIME_RU.items())
strs('kScrBlack', [n(b).strip(' .') for b in BLACK_WORDS])
pairs('kScrExtraSpeakers', [(n(a), b) for a, b in EXTRA_SPEAKERS.items()])
pairs('kScrCanonName', CANON_NAME.items())
STOP = ['в', 'во', 'на', 'с', 'со', 'и', 'а', 'но', 'же', 'уже', 'снова', 'опять', 'тоже', 'еще', 'так', 'как', 'вдруг',
        'одета', 'одет', 'одетая', 'одетый', 'стоит', 'стоя', 'сидит', 'сидя', 'вся', 'весь', 'своей', 'своем', 'своих',
        'по-прежнему', 'все', 'будто', 'словно', 'явно', 'тон', 'тоном', 'голосом', 'взглядом', 'лицом', 'видом',
        'глазами', 'сама', 'сам', 'к', 'от', 'из', 'за', 'до', 'для', 'при', 'ей', 'ему', 'нам', 'мне', 'нему', 'ней',
        'него', 'нее', 'его', 'ее', 'их', 'меня', 'тебя', 'ему', 'им', 'по', 'о', 'об', 'у', 'то', 'это', 'этом', 'чем',
        'что', 'чтобы', 'ли', 'бы', 'ну', 'даже', 'почти', 'всё', 'свою', 'свой', 'своим']
strs('kScrBlushStems', [n(x) for x in BLUSH_STEMS])
strs('kScrStop', sorted(set(n(s) for s in STOP)))
dst = os.path.join(ROOT, 'src', 'core', 'ScreenplayTables.inc')
open(dst, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
print('wrote', dst, len(lex), 'lexicon entries')
