"""tests/golden/tables.json (from the old builder) -> src/core/Tables.inc (C arrays)."""
import io
import json
import os

V1 = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
T = json.load(io.open(os.path.join(V1, "tests", "golden", "tables.json"), encoding="utf-8"))


def s(x):
    return json.dumps(x, ensure_ascii=False)


out = ["// GENERATED by tools/gen_tables.py from tests/golden/tables.json (old builder.py). Do not hand-edit.",
       "#pragma once",
       "struct KV { const char* k; const char* v; };",
       "struct KD { const char* k; double v; };",
       "struct KW { const char* k; const char* dot; const char* blossom; };"]


def kv(name, d, order=None):
    out.append("static const KV %s[] = {" % name)
    for k in (order or sorted(d)):
        out.append("    {%s, %s}," % (s(k), s(d[k])))
    out.append("    {nullptr, nullptr},")
    out.append("};")


def words(name, items):
    out.append("static const char* const %s[] = {%s, nullptr};" % (name, ", ".join(s(i) for i in items)))


kv("kRenames", T["RENAMES"])
kv("kSpeakers", T["SPEAKERS"])
words("kEffects", T["EFFECTS"])
words("kPositions", T["POSITIONS"])
words("kCommandNames", T["COMMAND_NAMES"])
words("kSpritePrefixes", T["GENRY_SPRITE_PREFIXES"])
out.append("static const KD kWalkXaligns[] = {")
for k in sorted(T["WALK_XALIGNS"]):
    out.append("    {%s, %r}," % (s(k), T["WALK_XALIGNS"][k]))
out.append("    {nullptr, 0},")
out.append("};")
out.append("static const KW kWeather[] = {")
for k in T["GENRY_WEATHER_ORDER"]:
    dot, blossom = T["GENRY_WEATHER"][k]
    out.append("    {%s, %s, %s}," % (s(k), s(dot), s(blossom)))
out.append("    {nullptr, nullptr, nullptr},")
out.append("};")
kv("kWeatherAliases", T["GENRY_WEATHER_ALIASES"])
words("kWeatherStop", T["GENRY_WEATHER_STOP"])
kv("kFilters", T["GENRY_FILTERS"], T["GENRY_FILTER_ORDER"])
kv("kFilterAliases", T["GENRY_FILTER_ALIASES"])
words("kFilterStop", T["GENRY_FILTER_STOP"])

io.open(os.path.join(V1, "src", "core", "Tables.inc"), "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
print("ids:", len(set(T["RENAMES"].values())), "aliases:", len(T["RENAMES"]), "command names:", len(T["COMMAND_NAMES"]))
